# Generated by Django 5.0.2 on 2024-06-04 07:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(default='', max_length=20)),
                ('adress', models.CharField(default='', max_length=20)),
                ('service', models.CharField(default='', max_length=225)),
                ('Email', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(blank=True, max_length=20)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('customer', models.CharField(blank=True, max_length=255)),
                ('end_user', models.CharField(blank=True, max_length=255)),
                ('project_currency', models.CharField(choices=[('', 'Select Currency'), ('SAR', 'Saudi Riyal (SAR)'), ('PKR', 'Pakistani Rupee (PKR)'), ('USD', 'US Dollar (USD)')], default='', max_length=3)),
                ('currency_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('payment_terms', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('project_manager', models.CharField(blank=True, max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('initial_so_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('change_order_1', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('change_order_2', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('change_order_3', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('change_order_4', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('total_so', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('bid_bom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bid_cogs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bid_va', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('design_cogs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('design_va', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('running_cogs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('running_va', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=255, unique=True)),
                ('group', models.CharField(choices=[('HR', 'HR'), ('Procurement', 'Procurement'), ('Marketing', 'Marketing'), ('Administrative', 'Administrative')], max_length=22)),
                ('full_access', models.BooleanField(default=False)),
                ('can_view_projects', models.BooleanField(default=False)),
                ('can_edit_projects', models.BooleanField(default=False)),
                ('can_view_employee', models.BooleanField(default=False)),
                ('can_edit_employee', models.BooleanField(default=False)),
                ('can_view_users', models.BooleanField(default=False)),
                ('can_edit_users', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeID', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='ProApp.employee')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProApp.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserEmployeeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProApp.employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'employee')},
            },
        ),
    ]
