# Generated by Django 5.0.2 on 2024-06-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProApp', '0002_alter_project_project_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_code',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
